### ISSUE TITLE
Crash while viewing runtime details during debug

### ISSUE THREAD

**Issue by ninjanomnom** [MCHSL/extools#23]
Environment details:
512.1488, 513.1506
tgstation (it's my pixel movement branch though so there are significant changes)

~~Whenever I get a runtime in debug if I spend some time to view the details of the runtime it ends up hard exiting the byond process.~~
Attempting to expand the vars of an object with no valid turf causes a crash (sometimes)

On a different runtime location I get the same symptoms but this shows up in the debug output:
`[main] Error responding to "variables": channel is empty and sending half is closed`

**Comment by MCHSL** [comment]
Fixed in https://github.com/MCHSL/extools/commit/731b6a9a167f9574c73763e94c32629f994d0a18
