### ISSUE TITLE
Proc type paths display as a memory address

### ISSUE THREAD

**Issue by ninjanomnom** [MCHSL/extools#27]
This is more of a feature requests but a more friendly display for proc type paths would be useful

**Comment by ninjanomnom** [comment]
@SpaceManiac Is this something on your end instead and should I make the issue over there?

**Comment by SpaceManiac** [comment]
The stringification needs to happen on the extools side, the langserver just needs to know it exists

**Comment by SpaceManiac** [comment]
Fixed in 15f7372ad9aa96354ce36b0750006e4802ba05e9
