### ISSUE TITLE
Failed to locate IsInContainer

### ISSUE THREAD

**Issue by ZeWaka** [MCHSL/extools#29]
BYOND Version: 513.1506+
DreamMaker Language Client Version: 0.1.6

Process:

1. Run VSCode with SpacemanDMM extension.
2. Go to the debug menu and run+debug.
3. See the error below, and then a successful DreamSeeker launch
4. Game runs normally, but without pausing on breakpoints/runtimes as expected.

![alt text](https://cdn.discordapp.com/attachments/485190298050363393/672478656970489876/unknown.png "Image:")

**Comment by ghost** [comment]
there's a new sig for this on newer 513: `55 8B EC 8B 45 10 83 EC 38 3C 0F 75 4D FF 75 14 E8 ?? ?? ?? ?? 83 C4 04 85 C0 74 3B 83 78 04 00 74 35 6A 0F FF 75 14 FF 75 10 E8`

**Comment by SpaceManiac** [comment]
@steamp0rt that's exactly what it was before

**Comment by ghost** [comment]
i guess i copied the wrong one

**Comment by Crossedfall** [comment]
Any plans on getting a patch out for this? It'd be cool to be able to upgrade to a version newer than 513.1506

**Comment by MCHSL** [comment]
Updated signature, in case of further problems make a new issue
