### ISSUE TITLE
Latest version is incompatible with 513.1539

### ISSUE THREAD

**Issue by Exxion** [MCHSL/extools#48]
Calling `maptick_initialize` seems to immediately crash Dream Daemon. Same probably goes for other calls but I didn't confirm that. I guess I could provide a crash log but it's not exactly hard to get the crash to happen.

EDIT: Title updated because I realized we were not actually using the release. Oops!

**Comment by sohpeach** [comment]
Should be fixed after the last few commits. There's a windows build @ https://ci.appveyor.com/project/MCHSL/extools/builds/37196531/job/gbyo64ou0ny01g75/artifacts.
